Update Boston Marathon sample
IgniteUI/igniteui-angular-samples pull request #2356
Opened 2020-11-17 07:06 UTC by hanastasov

Closes #2336

2020-11-18 14:22 UTC, kdinev requested changes

2020-11-18 14:22 UTC, kdinev commented on projects/app-crm/src/assets/images/grid/propeller-logo.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26.8 27.24"><defs><style>.cls-1,.cls-2,.cls-3{fill-rule:evenodd;}.cls-2{opacity:0.5;}.cls-2,.cls-3{isolation:isol
Change the auto-generated svg class names, because they pollute the global styles.

2020-11-19 11:50 UTC, ddincheva approved these changes

2020-11-19 11:55 UTC, kdinev approved these changes

2020-11-19 12:01 UTC, merged