Move CRM sample to separate application to improe loading time
IgniteUI/igniteui-angular-samples pull request #2372
Opened 2020-11-23 09:27 UTC by hanastasov

Closes #2369

2020-11-23 12:20 UTC, zdrawku requested changes
Font awesome is missing -     `<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">`

Also, the toolbar is missing, possibly because of this style:

```
.igx-grid-toolbar__title {
        display: none;
    }
```

Also, please consider the propeller image and input group to be responsive, example:

https://www.infragistics.com/angular-demos-lob/grid-crm

2020-11-23 13:41 UTC, HristoP96 submitted a review, later dismissed

2020-11-23 15:31 UTC, HristoP96 approved these changes

2020-11-24 09:47 UTC, zdrawku approved these changes

2020-11-24 09:47 UTC, merged