Add page title and meta description -vnext
IgniteUI/igniteui-angular-samples pull request #2395
Opened 2020-12-03 12:10 UTC by dobromirts

Closes #2390

2020-12-04 14:45 UTC, HristoP96 requested changes
The grid dynamic chart data title and description probably should be switched with the title and description of the finjs component

2020-12-04 14:47 UTC, HristoP96 requested changes

2020-12-04 14:47 UTC, HristoP96 commented on projects/app-lob/src/app/seo.service.ts
> +        title ? this.title.setTitle(title) : this.title.setTitle(this.defaultTitle);
```suggestion
        this.title.setTitle(title ?? this.defaultTitle)
```

2020-12-04 14:47 UTC, HristoP96 commented on projects/app-lob/src/app/seo.service.ts
> +        desc ? this.meta.updateTag({ name: 'description', content: desc }) : this.meta.updateTag({ name: 'description', content: this.defaultDesc })
```suggestion
        desc ? this.meta.updateTag({ name: 'description', content: desc }) : this.meta.updateTag({ name: 'description', content: this.defaultDesc })
```
```suggestion
        this.meta.updateTag({ name: 'description', content: desc ?? this.defaultDesc });
```

2020-12-07 14:25 UTC, HristoP96 requested changes
Requested changes are commented [here](https://github.com/IgniteUI/igniteui-angular-samples/pull/2396#pullrequestreview-546191167)

2020-12-11 10:36 UTC, HristoP96 approved these changes

2020-12-14 10:08 UTC, zdrawku approved these changes

2020-12-14 10:08 UTC, merged