Add page title and meta description -master
IgniteUI/igniteui-angular-samples pull request #2396
Opened 2020-12-03 12:21 UTC by dobromirts

Closes #2390

2020-12-07 14:21 UTC, HristoP96 requested changes
@zdrawku @aatanasov2 As we dicussed with @dobromirts the following changes must be applied to this PR:

- Since the SEO service will be a global service injected within the app.component.ts we need to add a app.component.ts.template for the live editing generation in order to not ship this [content](https://github.com/IgniteUI/igniteui-angular-samples/blob/master/src/app/app.component.ts) wtih our Stackblitz/CSB samples

- If a nested route is not configured with title nad description, the service must get its parent route title and description (if any, otherwise use the default ones). E.g. this [bottom nav](https://www.infragistics.com/angular-demos/layouts/tabbar-sample-3) sample has nested routings in it with these [configuraitons](https://github.com/IgniteUI/igniteui-angular-samples/blob/master/src/app/layouts/tabbar/tabbar-sample-3/tabbar.routing.module.ts). If the user goes to any of the nested routes, the title and the description of the page should not change if no description and title are added to the nested route configurations.

2020-12-07 14:21 UTC, HristoP96 commented on projects/app-lob/src/app/app.component.ts
> +        this.router.events.pipe(
This pipe chain of rxjs operators could be shorten into two operator invokes, like only filter and mergeMap

2020-12-11 12:52 UTC, HristoP96 approved these changes

2020-12-14 10:08 UTC, zdrawku approved these changes

2020-12-14 10:09 UTC, merged