Grid with Select sample
IgniteUI/igniteui-angular-samples pull request #2434
Opened 2021-01-14 15:31 UTC by valadzhov

Closes #1913

2021-01-27 13:40 UTC, IvayloG requested changes

2021-01-27 13:40 UTC, IvayloG commented on src/app/grid/grids-routing.module.ts
> +import {GridSelectComponent} from './grid-select/grid-select-sample.component'
Fix formating 
{GridSelectComponent} --> { GridSelectComponent }

2021-01-27 13:40 UTC, IvayloG commented on src/app/grid/grids.module.ts
> +import {GridSelectComponent} from './grid-select/grid-select-sample.component';
Fix formating
{GridSelectComponent} --> { GridSelectComponent }

2021-01-29 13:57 UTC, IvayloG submitted a review, later dismissed

2021-02-01 08:18 UTC, IvayloG submitted a review, later dismissed

2021-02-03 05:02 UTC, IvayloG commented on src/app/grid/grid-select/grid-select-sample.component.scss
> +}
I expect this PR should include the igxSelect styling ( last committed in the master branch ) via https://github.com/IgniteUI/igniteui-angular-samples/pull/2440/commits/3e8545121551d184b912f1916eac14e16641c001

2021-02-03 10:14 UTC, IvayloG approved these changes

2021-02-03 11:32 UTC, Lipata approved these changes

2021-02-03 11:51 UTC, merged