Replace node-sass with dart-sass -vnext
IgniteUI/igniteui-angular-samples pull request #2561
Opened 2021-03-31 07:23 UTC by dobromirts

Closes #2558

2021-03-31 13:43 UTC, zdrawku commented
46 minutes build time .. previously it was 8 :(
![image](https://user-images.githubusercontent.com/11193764/113153955-38984e80-9240-11eb-8fd7-d8997a8baff4.png)

2021-04-02 07:32 UTC, simeonoff requested changes

2021-04-02 07:32 UTC, simeonoff commented on src/app/data-entries/select/select-header-footer/select-header-footer.component.scss
> +    $item-border-color: igx-color('grays', 700),
This is wrong, it should be:

```suggestion
    $item-background: igx-color($color: 'grays', $variant: 300),
    $item-text-color: igx-color($color: 'grays', $variant: 700),
    $item-hover-background: igx-color($color: 'grays', $variant: 400),
    $item-hover-text-color: igx-color($color: 'grays', $variant: 700),
    $item-border-color: igx-color($color: 'grays', $variant: 700),
```

2021-04-02 07:34 UTC, simeonoff commented
> 46 minutes build time .. previously it was 8 :(
> ![image](https://user-images.githubusercontent.com/11193764/113153955-38984e80-9240-11eb-8fd7-d8997a8baff4.png)

Something must be very wrong. You can expect some slowdown if the build process uses some wrapper to call the dart sass binary, however, not in the scale of 5x. We must investigate further before we merge this PR.

2021-04-06 13:01 UTC, dobromirts commented
After some research i found that, the the sass package on NPM is compiled to JS from Dart, so it has the same behavior as native Dart Sass (unlike the node-sass package, which is based on the deprecated libsass), just with a performance penalty due to running in JS (which shouldn't be a practical issue except for very large projects).
The pure JS version is slower than the stand-alone executable (https://sass-lang.com/dart-sass).
For projects that have a large codebase of sass files that need to be compiled and performance is important,
the DartVM executable version should be preferred or integrated in the project [cli-issue](https://github.com/angular/angular-cli/issues/15899). 
The option to use the fast DartVM executable version of dart-sass, should be possible with this library
https://github.com/sass/embedded-host-node as mention also in [here](https://github.com/webpack-contrib/sass-loader/issues/774).

2021-05-18 08:33 UTC, dobromirts commented
The issue with the build time increase is also mentioned in https://github.com/angular/components/issues/22676 , https://github.com/angular/angular-cli/issues/20792.

2021-07-27 10:45 UTC, simeonoff approved these changes

2021-07-29 08:23 UTC, merged