Update re-templating grid filter 2621
IgniteUI/igniteui-angular-samples pull request #2630
Opened 2021-04-23 08:35 UTC by zhosti

Changing date filter in all grid samples for re-templating filter cell 

closes #2621

2021-04-23 14:31 UTC, gedinakova requested changes

2021-04-23 14:31 UTC, gedinakova commented on src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.html
> +            <igx-date-picker [value]="getFilterValue(column)" (valueChange)="onDateSelected($event, column)" mode="dialog">
In order to achieve the same appearance as the other three filter cells, we need to change the date picker template a bit more:
```
<igx-date-picker #dp [value]="getFilterValue(column)" (valueChange)="onDateSelected($event, column)" mode="dialog"
                [displayDensity]="'compact'" placeholder="Filter..." type="box">
                <igx-picker-toggle (click)="dp.open()" igxPrefix>
                    <igx-icon>search</igx-icon>
                </igx-picker-toggle>
                <igx-picker-clear *ngIf="value" igxSuffix (click)="dp.clear()">
                    <igx-icon>clear</igx-icon>
                </igx-picker-clear>
            </igx-date-picker>
```

2021-04-23 14:31 UTC, gedinakova commented on src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.ts
>      public onDateSelected(event, column: IgxColumnComponent) {
This code needs to be changed as follows in order for the clear button to work and actually clear the filter:
```
if (!event) {
            this.clearInput(column);
            return;
        }

        this._filterValues.set(column, event);
        this.grid1.filter(column.field, event, IgxDateFilteringOperand.instance().condition('equals'),
                column.filteringIgnoreCase);
```

2021-04-26 09:23 UTC, gedinakova requested changes

2021-04-26 09:23 UTC, gedinakova commented on src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.ts
> +    public formatter(date: Date): string {
This change is wrong - this formatter is used in columns like Debut, Launch Date, etc. They are supposed to show the year only. Currently, the formatter doesn't handle well the underlying value and always shows 1/1/1970.

2021-04-26 10:59 UTC, wnvko requested changes

2021-04-26 10:59 UTC, wnvko commented on src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.html
> +                <igx-picker-toggle igxPrefix (click)="dp.open()">
do not handle `click` in the `igx-picker-toggle` - this should be handled by date picker

2021-04-26 10:59 UTC, wnvko commented on src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.html
> +                <igx-picker-clear *ngIf="value" igxSuffix (click)="dp.clear()">
do not handle `click` in the `igx-picker-clear` - this should be handled by date picker

2021-04-26 10:59 UTC, wnvko commented on src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.html
> +            <igx-picker-toggle igxPrefix (click)="dp.open()">
do not handle `click` in the `igx-picker-toggle` - this should be handled by date picker

2021-04-26 10:59 UTC, wnvko commented on src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.html
> +            <igx-picker-clear *ngIf="value" igxSuffix (click)="dp.clear()">
do not handle `click` in the `igx-picker-clear` - this should be handled by date picker

2021-04-26 10:59 UTC, wnvko commented on src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.html
> +                    <igx-picker-toggle igxPrefix (click)="dp.open()">
do not handle `click` in the `igx-picker-toggle` - this should be handled by date picker

2021-04-26 10:59 UTC, wnvko commented on src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.html
> +                    <igx-picker-clear *ngIf="value" igxSuffix (click)="dp.clear()">
do not handle `click` in the `igx-picker-clear` - this should be handled by date picker

2021-04-26 15:20 UTC, wnvko submitted a review, later dismissed

2021-04-27 09:46 UTC, gedinakova requested changes

2021-04-27 09:46 UTC, gedinakova commented on src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.ts
> +    public displayDateFormat = 'MMM d, y';
Let's update this format so it matches the data cells' format - 'M/d/y'.

2021-04-27 09:46 UTC, gedinakova commented on src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.ts
> +    public displayDateFormat = 'MMM d, y';
Let's update this format so it matches the data cells' format - 'M/d/y'.

2021-04-27 12:26 UTC, gedinakova approved these changes

2021-04-27 13:46 UTC, merged