treegrid group by load on demand sample - vNext
IgniteUI/igniteui-angular-samples pull request #2667
Opened 2021-05-13 12:53 UTC by igdmdimitrov

Closes #2658

2021-05-21 12:26 UTC, DiyanDimitrov requested changes

2021-05-21 12:26 UTC, DiyanDimitrov commented on src/app/tree-grid/tree-grid-group-by-load-on-demand-sample/tree-grid-group-by-load-on-demand-sample.component.html
> +        <igx-column field="OrderDate" header="Order Date" width="200px" [formatter]="formatDate">
```suggestion
        <igx-column field="OrderDate" header="Order Date" width="200px" dataType="date">
```

2021-05-21 12:26 UTC, DiyanDimitrov commented on src/app/tree-grid/tree-grid-group-by-load-on-demand-sample/tree-grid-group-by-load-on-demand-sample.component.html
> +        <igx-column field="UnitPrice" header="Unit Price" width="150px" [formatter]="formatCurrency" dataType="number">
```suggestion
        <igx-column field="UnitPrice" header="Unit Price" width="150px" dataType="currency">
```

2021-05-21 12:26 UTC, DiyanDimitrov commented on src/app/tree-grid/tree-grid-group-by-load-on-demand-sample/tree-grid-group-by-load-on-demand-sample.component.ts
> +    }
We could use the built-in column data types instead.
```suggestion
```

2021-05-21 12:26 UTC, DiyanDimitrov commented on src/app/tree-grid/tree-grid-group-by-load-on-demand-sample/tree-grid-group-by-load-on-demand-sample.component.ts
> +        this.treeGrid.reflow();
Calling `reflow` seems unnecessary.
```suggestion
```

2021-05-21 13:46 UTC, DiyanDimitrov submitted a review, later dismissed

2021-05-27 15:40 UTC, gedinakova commented
@igdmdimitrov An NG0100 error is thrown in the console on loading the sample caused by the column hiding in ngAfterViewInit. I suggest we set the three columns' hidden property in the template and remove this code.

2021-05-27 15:51 UTC, gedinakova commented
@igdmdimitrov On adding or removing a column from the group-by area, the grid's header is not refreshed immediately and the column is present/not present until expansion.

2021-05-28 10:12 UTC, gedinakova approved these changes

2021-05-28 11:35 UTC, DiyanDimitrov approved these changes

2021-05-28 11:51 UTC, merged