Create date & time picker form samples-master
IgniteUI/igniteui-angular-samples pull request #2703
Opened 2021-06-04 08:01 UTC by PlamenaMiteva

Closes #2660

The following samples show how the date & time picker could act as a Date & Time Picker Component:

date and time picker using ngModel bound to one and the same date object in a template-driven form

date and time picker in a reactive form with a possible workaround that updates the value of the date picker on time picker value change and vice versa

2021-06-07 11:35 UTC, StefanIvanov commented
@PlamenaMiteva please update the samples accordingly: 

set the total form width to 400px
make the date picker 55% and time picker 45% with 16px in between

Also show just once the date object and display it in the paragraph with form validity like so:

<img width="433" alt="Screenshot 2021-06-07 at 14 34 03" src="https://user-images.githubusercontent.com/1702064/121009942-6d270a00-c79d-11eb-8ddc-d68a21021d22.png">

2021-06-09 09:06 UTC, StefanIvanov submitted a review, later dismissed

2021-06-10 08:59 UTC, StefanIvanov approved these changes

2021-06-11 04:47 UTC, jackofdiamond5 approved these changes

2021-06-11 07:19 UTC, Lipata requested changes
StackBlitz and CodeSandBox samples are nor working

2021-06-15 09:18 UTC, jackofdiamond5 approved these changes

2021-06-15 11:19 UTC, merged