Remove localization samples configs shorten path -vnext
IgniteUI/igniteui-angular-samples pull request #2733
Opened 2021-07-01 08:33 UTC by dobromirts

Closes #2731

2021-07-06 12:15 UTC, zdrawku requested changes
I've noticed two problems, the first sample of the topic is not loaded because of missing package - its strange that the particular package is present ..
![image](https://user-images.githubusercontent.com/11193764/124597945-c05bad80-de6c-11eb-9b90-8d13d0a83cd1.png)

2021-07-06 12:15 UTC, zdrawku commented on live-editing/configs/LocalizationConfigGenerator.ts
> +            additionalDependencies: ['igniteui-angular-i18n'],
additionalFiles should not be removed as the sample in stackblitz will return an error. Is there a reason to remove adding the nwindData.ts?

2021-07-07 16:36 UTC, dobromirts commented
> The first sample of the topic is not loaded because of missing package - its strange that the particular package is present ..
> ![image](https://user-images.githubusercontent.com/11193764/124597945-c05bad80-de6c-11eb-9b90-8d13d0a83cd1.png)

This behaviour is due to the usage of  resources as 'IgxResourceStrings'  which are provided from this package and when they are assigned to 'locales' property in the 'OnInit' stackblitz can not find and use this package anymore.

2021-07-08 07:06 UTC, zdrawku approved these changes

2021-07-08 07:06 UTC, merged