fix(toolbar): wrap actions in toolbar-actions
IgniteUI/igniteui-angular-samples pull request #2866
Opened 2021-11-18 09:53 UTC by Svetloslav15

Closes #2865

2021-11-19 12:32 UTC, hanastasov requested changes
Please revert the changes for following files:
src/app/grid/grid-clipboard-operations-sample/grid-clipboard-operations-sample.component.html

src/app/hierarchical-grid/column-selection/hierarchical-grid-column-selection.component.html

src/app/tree-grid/tree-grid-clipboard-operations-sample/tree-grid-clipboard-operations-sample.component.html

2021-11-19 12:41 UTC, hanastasov submitted a review, later dismissed

2021-11-19 12:43 UTC, hanastasov commented
@DiyanDimitrov please let us know if you are ok with these changes - show the buttons for all samples that were rendering the toolbar anyway.

2021-11-19 14:38 UTC, DiyanDimitrov commented
> @DiyanDimitrov please let us know if you are ok with these changes - show the buttons for all samples that were rendering the toolbar anyway.

I would rather leave the samples as they were before. If the sample is for column hiding I don't think we need to distract the customers with pinning and export. Exporting is especially risky to be enabled everywhere since not all grids are exported correctly (especially if they have templated columns).

2021-11-19 14:51 UTC, hanastasov commented
@DiyanDimitrov Would it be ok to revert the changes for samples that are specific (like hiding sample,, which does not need to render the other actions), and revert adding exporting action for all samples

2021-11-19 15:16 UTC, DiyanDimitrov commented
> @DiyanDimitrov Would it be ok to revert the changes for samples that are specific (like hiding sample,, which does not need to render the other actions), and revert adding exporting action for all samples

Sounds good to me.

2021-11-22 07:34 UTC, DiyanDimitrov requested changes

2021-11-22 07:34 UTC, DiyanDimitrov commented on src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.html
> +                <igx-grid-toolbar-exporter></igx-grid-toolbar-exporter>
```suggestion
```

2021-11-22 07:34 UTC, DiyanDimitrov commented on src/app/tree-grid/tree-grid-excel-style-filtering-sample-1/tree-grid-excel-style-filtering-sample-1.component.html
> +                <igx-grid-toolbar-exporter></igx-grid-toolbar-exporter>
```suggestion
```

2021-11-22 07:34 UTC, DiyanDimitrov commented on src/app/tree-grid/tree-grid-excel-style-filtering-sample-2/tree-grid-excel-style-filtering-sample-2.component.html
> +                <igx-grid-toolbar-exporter></igx-grid-toolbar-exporter>
```suggestion
```

2021-11-22 08:19 UTC, DiyanDimitrov approved these changes

2021-11-22 08:58 UTC, zdrawku approved these changes

2021-11-22 08:58 UTC, merged