Pbozhinov/another pivot sample
IgniteUI/igniteui-angular-samples pull request #2921
Opened 2022-02-10 07:16 UTC by 3phase

Todo: 
 - Filter Aggregation
 - Features

2022-02-17 07:48 UTC, skrustev approved these changes

2022-02-18 13:19 UTC, ChronosSF requested changes
Please add data selector

2022-02-18 14:30 UTC, dkamburov commented
@ChronosSF added the data selector

2022-02-18 16:11 UTC, dkamburov submitted a review, later dismissed

2022-02-18 16:54 UTC, ChronosSF approved these changes

2022-02-21 07:30 UTC, dkamburov approved these changes

2022-02-21 07:30 UTC, merged