Data Selector Sample
IgniteUI/igniteui-angular-samples pull request #2928
Opened 2022-02-17 11:19 UTC by 3phase

Closes #2924

2022-02-17 17:29 UTC, dkamburov commented on src/app/pivot-grid/pivot-datasource/pivot-datasource-sample.component.ts
> +                memberFunction: (data) => data.Region,
I don't think that the `memberFunction` is needed for this scenario

2022-02-18 09:58 UTC, MayaKirova commented
The pivot items have a lower zindex than the grid so when you drag them near the grid they disappear behind it:
![list-items-zindex](https://user-images.githubusercontent.com/10397980/154660174-4b78da25-f677-48a0-a425-f2b599739b03.gif)

I can't reproduce the same in the dev samples, so there's probably some styling in the demos that causes this.

2022-02-18 10:10 UTC, MayaKirova submitted a review, later dismissed

2022-02-21 12:43 UTC, dkamburov commented
@3phase The height of the grid should match the data selector, also there is no live-editing configuration for the sample

2022-02-22 09:13 UTC, MayaKirova commented
@3phase @dkamburov 

- [ ] The sample does not fit in the size available in the docs. Either it should be smaller or the size in the docs should be updated to match:

![image](https://user-images.githubusercontent.com/10397980/155096468-1ef53f75-2d29-4d0f-be9a-cfe9b4d3fa6e.png)

- [ ] Pivot selector z-index here seems to be lower than the grid. 

![image](https://user-images.githubusercontent.com/10397980/155096876-1a1ee753-378b-4eb9-8349-4c252a189c07.png)

- [ ] We should disable column selection similar to the features sample, since it's not a pivot specific feature.

- [ ] The current way the dimensions are organized will always create empty values since specific Dates are grouped in the rows while the Years are grouped in the columns. So specific dates will always have a whole column section with no values (i.e. all 2019 dates will have empty value when you scroll to the 2018 group and vice versa).
![image](https://user-images.githubusercontent.com/10397980/155098318-dfba882a-ac68-4522-967b-ff11da89cd13.png)

It would make more sense to group date related values in one dimension so that you see meaningful aggregations for it.
For example rows can contain some date hierarchy (year -> month -> date), and everything else can be grouped in the columns or vice versa.

2022-02-22 09:15 UTC, MayaKirova requested changes
@3phase @dkamburov 

- [x] The sample does not fit in the size available in the docs. Either it should be smaller or the size in the docs should be updated to match:

![image](https://user-images.githubusercontent.com/10397980/155096468-1ef53f75-2d29-4d0f-be9a-cfe9b4d3fa6e.png)

- [ ] Pivot selector z-index here seems to be lower than the grid. 

![image](https://user-images.githubusercontent.com/10397980/155096876-1a1ee753-378b-4eb9-8349-4c252a189c07.png)

- [x] We should disable column selection similar to the features sample, since it's not a pivot specific feature.

- [x] The current way the dimensions are organized will always create empty values since specific Dates are grouped in the rows while the Years are grouped in the columns. So specific dates will always have a whole column section with no values (i.e. all 2019 dates will have empty value when you scroll to the 2018 group and vice versa).
![image](https://user-images.githubusercontent.com/10397980/155098318-dfba882a-ac68-4522-967b-ff11da89cd13.png)

It would make more sense to group date related values in one dimension so that you see meaningful aggregations for it.
For example rows can contain some date hierarchy (year -> month -> date), and everything else can be grouped in the columns or vice versa.

2022-02-22 09:20 UTC, dkamburov commented
The size of sample in topic is updated in - https://github.com/IgniteUI/igniteui-docfx/pull/3130

2022-02-22 11:22 UTC, 3phase commented
@MayaKirova the requested changes are applied

2022-02-22 11:27 UTC, dkamburov commented
@3phase 
The filters from data selector are cut off
![image](https://user-images.githubusercontent.com/1182001/155123107-fa19df82-2a8d-42ed-a994-12cf8f04fff3.png)

2022-02-22 15:51 UTC, MayaKirova approved these changes

2022-02-22 21:04 UTC, merged