Add cross cell validation sample.
IgniteUI/igniteui-angular-samples pull request #3083
Opened 2022-08-31 16:50 UTC by skrustev

2022-09-02 14:16 UTC, MayaKirova reviewed
Looks good. Only thing I noticed that I'm not sure if intended is that it collects only the custom errors, the default ones (like required, email etc) do not show in the pinned cell.

![image](https://user-images.githubusercontent.com/10397980/188168710-86169432-af6e-4aa2-8b05-d2f9e8751d6a.png)

2022-09-07 08:23 UTC, MayaKirova requested changes

2022-09-07 08:23 UTC, MayaKirova commented on src/app/grid/grid-validator-service-cross-cell/grid-validator-service-cross-cell.component.ts
> +    public formCreateHandler(formGroup: FormGroup) {
We changed the event arg to IGridFormGroupCreatedEventArgs. This will need update.

2022-09-08 08:18 UTC, MayaKirova approved these changes

2022-09-08 09:21 UTC, mddragnev commented
@skrustev 
One thing I found is in the tree grid, you have set a max validator on the `age` column but there is not a handler in the stateMessage for that validator. Once this validator is invalid then the row valid column count is as invalid but there is no message.
And a side note, in the tree grid sample if we pin the row valid column on the right, IMO we should make the width of the grid (or width of some of the columns) should be less because the tooltip is getting cut at the end.

2022-09-09 12:38 UTC, MayaKirova approved these changes

2022-09-09 13:58 UTC, merged