feat(list): adding list item selection sample
IgniteUI/igniteui-angular-samples pull request #3087
Opened 2022-09-08 13:36 UTC by kdinev

Adding a new sample showing how to implement selected styles to list items.

2022-09-08 14:30 UTC, wnvko requested changes
There is no config added for this sample in `live-editing/configs/ListConfigGenerator.ts`

2022-09-08 14:30 UTC, wnvko commented on src/app/lists/list/list-item-selection/list-item-selection.component.html
> +            <igx-icon igxListAction [style.color]="contact.isFavorite ? 'orange' : 'lightgray'" (click)="toggleFavorite(contact)">star</igx-icon>
clicking on the favorite start will also select the list item. IMO this is not ok. You can pass event to `toggleFavoriet` and call `event.stopPropagation` .

2022-09-08 14:30 UTC, wnvko commented on src/app/lists/list/list-item-selection/list-item-selection.component.ts
> +    public displayDensities;
is this leftover?

2022-09-08 14:53 UTC, wnvko submitted a review, later dismissed

2022-09-09 08:26 UTC, wnvko submitted a review, later dismissed

2022-09-09 13:59 UTC, wnvko requested changes

2022-09-09 13:59 UTC, wnvko commented on live-editing/configs/ListConfigGenerator.ts
> +                    'IgxInputGroupModule', 'IgxRippleModule', 'ListItemSelectionComponent'],
`IgxRippleModule` is not needed anymore here and in `ngImports`

2022-09-09 13:59 UTC, wnvko commented on src/app/lists/list/list-item-selection/list-item-selection.component.ts
> +    constructor() { }
empty constructor could be deleted.

2022-09-12 09:58 UTC, wnvko commented on live-editing/configs/ListConfigGenerator.ts
> +                    'IgxInputGroupModule', 'IgxRippleModule']
```suggestion
                    'IgxInputGroupModule']
```

2022-09-12 11:02 UTC, wnvko submitted a review, later dismissed

2022-09-12 11:47 UTC, kdinev commented
@wnvko Have you also tested it?

2022-09-12 13:01 UTC, wnvko approved these changes

2022-09-12 13:05 UTC, merged