fix(FinJSDemoComponent): Fix finjs category chart
IgniteUI/igniteui-angular-samples pull request #3122
Opened 2022-10-12 11:40 UTC by katherinedragieva

Closes #3111

2022-10-12 11:48 UTC, hanastasov requested changes

2022-10-12 11:48 UTC, hanastasov commented on projects/app-lob/src/app/grid-finjs/main.component.ts
> +    public chartData: any[] = [];
Good practice is to always type, and type to `any` only if really really needed. Not sue if this is the case.

2022-10-12 11:48 UTC, hanastasov commented on projects/app-lob/src/app/grid-finjs/main.component.ts
> +            this.finGrid.grid.data.filter(data => {
There is a forEach loop. and inside it there is filter, which again loops through all data records. Not a viable solution. This increases complexity and iterations a lot. Must be changed.

2022-10-14 12:33 UTC, dobromirts commented
The chart is still not themed based on the selected dark theme and preserves the default styles.
![chart-theming](https://user-images.githubusercontent.com/46093564/195847942-b419cc4a-d3a8-47a0-a6c2-b59c454fb1cc.png)

2022-10-18 06:49 UTC, hanastasov approved these changes

2022-10-18 08:14 UTC, hanastasov commented on projects/app-lob/src/app/grid-finjs/main.component.ts
> +        this.finGrid.grid.data.filter(data => {
Instead of going through all grid data and compare the id, grid API should be used for such cases. It is more intuitive and more readable.

2022-10-18 08:46 UTC, hanastasov requested changes
USe grid api instead

2022-10-18 10:51 UTC, hanastasov approved these changes

2022-10-19 07:28 UTC, merged