Replace tree grid FOODS_DATA with orders data
IgniteUI/igniteui-angular-samples pull request #3232
Opened 2023-01-12 15:50 UTC by PlamenaMiteva

Closes #2941

2023-01-19 13:31 UTC, igdmdimitrov commented on src/app/tree-grid/tree-grid-summary-sample/tree-grid-summary-sample.component.html
> +        y]="true" [dataType]="'boolean'">
Also, `<igx-column #col field="ID" header="Product ID">` should be changed to `<igx-column #col field="ID" header="Order ID">`

2023-01-19 13:38 UTC, igdmdimitrov commented on src/app/tree-grid/tree-grid-excel-style-filtering-sample-1/tree-grid-excel-style-filtering-sample-1.component.html
> +        <igx-column field="Delivered" header="Deliverued" [dataType]="'boolean'">
**Fix this in all files**

```suggestion
        <igx-column field="Delivered" header="Delivered" [dataType]="'boolean'">
```

2023-01-27 13:45 UTC, igdmdimitrov requested changes

2023-01-27 13:45 UTC, igdmdimitrov commented on src/app/tree-grid/tree-grid-conditional-cell-style-sample/tree-grid-conditional-cell-style-sample.component.html
> +        <igx-column field="Discontinued" header="Discontinued" [sortable]="true" [disableHiding]="true" [dataType]="'boolean'">
```suggestion
        <igx-column field="Delivered" header="Delivered" [sortable]="true" [disableHiding]="true" [dataType]="'boolean'">
```

2023-01-27 13:45 UTC, igdmdimitrov commented on src/app/tree-grid/tree-grid-conditional-cell-style-sample/tree-grid-conditional-cell-style-sample.component.html
> +                <img *ngIf="!val" src="assets/images/grid/expired.png" title="Discontinued" alt="Discontinued" />
```suggestion
                <img *ngIf="val" src="assets/images/grid/active.png" title="Delivered" alt="Delivered" />
                <img *ngIf="!val" src="assets/images/grid/expired.png" title="Undelivered" alt="Undelivered" />
```

2023-01-27 13:45 UTC, igdmdimitrov commented on src/app/tree-grid/tree-grid-summary2-sample/tree-grid-summary2-sample.component.html
>      <igx-column #col field="Name" header="Product Name" [hasSummary]="true">
Fix this and the `Discontinued` and `Added Date`.

```suggestion
    <igx-column #col field="Name" header="Order Name" [hasSummary]="true">
```

2023-03-10 09:00 UTC, kdinev commented
@Lipata Could we change the ORDERS_DATA to not be a function and we should get this PR merged?

2023-03-22 10:18 UTC, kdinev submitted a review, later dismissed

2023-03-22 10:19 UTC, kdinev commented
@igdmdimitrov Could you review again?

2023-03-22 11:55 UTC, igdmdimitrov approved these changes

2023-04-19 09:59 UTC, Lipata approved these changes

2023-04-19 10:00 UTC, merged